---
# tasks file for zimbra
    - name: kopieer de template files naar target host
      copy:
        src: "{{ item }}"        
        dest: /tmp
      with_fileglob:
        - "/etc/ansible/roles/zimbra/templates/zimbra*"
      become: true

    - name: update de packages
      yum:
        name: '*'
        state: latest
       
    - name: installeer chrony
      become: yes
      yum:
        name: chrony
        state: latest

    - name: Zet juiste timezone
      become: true
      command: timedatectl set-timezone {{ timezone }}

    - name: installeer epel repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: installeer de zimbra installer script
      get_url:
        url: https://download.zextras.com/zcs-9.0.0_OSE_RHEL8_latest-zextras.tgz
        dest: /root

    - name: pak de zimbra installer script uit
      unarchive:
        src: /root/zcs-9.0.0_OSE_RHEL8_latest-zextras.tgz
        dest: /root
        remote_src: yes

    - name: installeer prereq script
      git:
        repo: https://github.com/jmutai/scripts.git
        dest: /root/scripts

    - name: Execute zimbra_install_prereqs_rhel.sh script
      shell: ./zimbra_install_prereqs_rhel.sh -s < /tmp/zimbra_install_prereqs
      args:
        chdir: /root/scripts/zimbra/

    - name: Execute zimbra_bind_setup_rhel.sh script
      shell: ./zimbra_bind_setup_rhel.sh -s < /tmp/zimbra_install_setup
      args:
        chdir: /root/scripts/zimbra/

    - name: Execute zimbra installer script
      shell: ./install.sh -s < /tmp/zimbra_installer_antwoorden
      args:
       chdir: /root/zcs-9.0.0_ZEXTRAS_20221203.RHEL8_64.20221216110429
